#ifndef HPP_IDHEADER
#define HPP_IDHEADER

#define INVALID_ID 0
#define DATARATE_ID 1
#define FREQUENCYRESPONSE_ID 2
#define IMPULSERESPONSE_ID 3
#define LIKELIHOOD_ID 4
#define IQ_ID 5
#define SIGNALTIME_ID 6
#define SPECTRUM_ID 7
#define WATERFALL_ID 8

#endif